### ISSUE TITLE
"This module need 96 kHz" message does not disappear

### ISSUE THREAD

**Issue by Elias035** [ch-nry/VCV_nozori#11]
All the modules have the same issue. I tried changing to 96kHz, restarting Rack, saving and reloading the patch with 96kHz. Is this meant to happen?

I'm using Rack 1.1.6, the modules are 1.1.5, I am running MacOS Catalina 10.15.4.

**Comment by ch-nry** [comment]
no, it's not. The message should disappear after few second when using the wrong sample rate, and should never appear when using the correct sample rate.
It's a bug I can't reproduce here, and I don't know how to fix.

**Comment by Elias035** [comment]
Hey.
Thanks for making this clear and sharing your work with the community.
Dont worry about it, I just wanted to share the information. No need to fix this of you dont feel it is beneficial.

Happy and healthy times.
Elias

**Comment by ch-nry** [comment]
I would like to fix this problem, but I don't know how. 
Transparency is only experimental in VCV rack...

best

**Comment by jaortega-net** [comment]
Hi. I have the same issue. I can tell that first time i tried to use nozoid modules, rack was in 44.1 but changed it cause 96 is the freq i work with. So all later sessions were in 96 and still saying that needs what the actual sampling rate is.
I have unsubsribed, deleted nozoid folder plugins, subscribed again and update rack. Doesnt work.
1.1.6 on catalina too.

Thank you so much.

**Comment by ch-nry** [comment]
thanks for the report, It look like it' a problem between VCV alpha channel with catalina...

**Comment by joshdavenport** [comment]
Also seeing this issue in Catalina 10.15.4 with VCV 1.1.6

![image](https://user-images.githubusercontent.com/757828/90537167-e6089700-e174-11ea-9f4a-32daec5b7482.png)

Anything I could do to help debug?

**Comment by ch-nry** [comment]
Since this problem only appear on osX catalina, and I use linux, I don't know how to debug it. Is there a developer here that is OK to help me? You will need to compile the plug-in from source, in order to test few hypothesis...

**Comment by joshdavenport** [comment]
I believe I've managed to fix this. See below for the behaviour I'm now seeing from a local build. The warning is even correctly hidden in the module selection menu.

![2020-08-25 22 46 07](https://user-images.githubusercontent.com/757828/91231489-3eb3d300-e725-11ea-8acc-b5989622b961.gif)

Not sure I can fully explain how it was broken only on Catalina (or mac generally, whatever) and not on Linux. In any case, hopefully this will also work on your linux machine @ch-nry. That would be a positive sign that this will work everywhere IMO.

Creating a pull request now.

**Comment by ch-nry** [comment]
version 1.1.7 is available via automatic update in VCV. 
Is the fix working for catalina user?

**Comment by joshdavenport** [comment]
Yep, all good! 👍 

![Screenshot 2020-09-01 at 11 30 14](https://user-images.githubusercontent.com/757828/91839158-82876a80-ec46-11ea-925e-ba7d80304350.png)

![Screenshot 2020-09-01 at 11 30 41](https://user-images.githubusercontent.com/757828/91839188-93d07700-ec46-11ea-95be-f4df83edeb47.png)

**Comment by ch-nry** [comment]
good!
I did not understand the problem, but i'm glad it's fixed.
thanks!
