### ISSUE TITLE
VCV Rack crashes when I open a pair of Nozori modules

### ISSUE THREAD

**Issue by Toybulldog** [ch-nry/VCV_nozori#13]
Hallo 
https://youtu.be/IqwVQF_lAOY
[VCV Rack log.txt.zip](https://github.com/ch-nry/VCV_nozori/files/5199955/VCV.Rack.log.txt.zip)

**Comment by ch-nry** [comment]
I confirm the problem

**Comment by ch-nry** [comment]
should be fixed with version 1.1.8
![Capture du 2020-09-15 21-23-29](https://user-images.githubusercontent.com/1230363/93256620-df813580-f79b-11ea-9249-2521dd414034.png)
