### ISSUE TITLE
Migration to V2

### ISSUE THREAD

**Issue by netboy3** [ch-nry/VCV_nozori#18]
I've just completed migrating the plugin to V2 and making a few enhancements. I've added a dark theme in the spirit of following the actual hardware modules. I've posted a PR #17 for your review and merge. I'm attaching below pre-built test binaries of the plugin for all three platforms. Please make sure to open the zip file below and pick the plugin binary for your platform. The binaries were built from modified sources posted [to my repository](https://github.com/netboy3/Nozori-vcvrack-plugin/tree/v2) and built as of commit da9fc03.

[Nozoid-2.1.3.zip](https://github.com/ch-nry/VCV_nozori/files/7798604/Nozoid-2.1.3.zip)

**Comment by ch-nry** [comment]
wow, thanks for your work. 
After a quick look, I found that the "bad sample rate" warning is not updated when the sample rate change. (it appear or not depending on the SR when the module is created, but did not disappear (or appear) when the SR is changed).
Anyway, I'll merge as soon as I have a bit more time.
thanks!

**Comment by netboy3** [comment]
You are very welcome! What you describe is actually not the module's code issue but rather the way Rack behaves. I noticed it too and put a debugger on the code. Rack does not change the value of args.sampleRate unless there's an active audio interface. I don't know if that's how Rack1 behaved, but that's how Rack2 works. It's actually logical as usually for most digital audio systems, clock and sync are derived from the digital audio clock source. Try it out - just drop an audio-8 or audio-16 module into the patch (no need to even connect it), make sure to configure it to a proper interface so it's active, and the warnings will work fine on SampleRate changes.

**Comment by ch-nry** [comment]
oh, yes, you are right!

**Comment by netboy3** [comment]
Thanks for merging. I hope you'll be able to find a few minutes to request an update in the VCV library. Have a happy new year.

**Comment by ch-nry** [comment]
I just made the request. Happy new year, and thanks again!
