### ISSUE TITLE
Can't compile it on windows

### ISSUE THREAD

**Issue by vcvrackideas** [ch-nry/VCV_nozori#2]
Hi! Thanks for your modules but I can't compile it on windows.
I'm getting this error
Artem@WIN-NNS56LESTDV MINGW64 ~/rack-sdk/dep/vcv_nozori
# make
Makefile:22: ../plugin.mk: No such file or directory

**Comment by ch-nry** [comment]
I think it's because you did not set "RACK_DIR". I change the makefile so you don't have to.
should be fixed with commit #3390d2ad884618fad324d4fe248921654e33d90c
