### ISSUE TITLE
96khz modules don't want to work with 48khz ones 

### ISSUE THREAD

**Issue by vcvrackideas** [ch-nry/VCV_nozori#3]
So is there any chance to marry them? 
![2019-10-11_12-17-22](https://user-images.githubusercontent.com/42435368/66640239-422f9000-ec21-11e9-8687-ff3575bef058.png)
![2019-10-11_12-17-37](https://user-images.githubusercontent.com/42435368/66640240-422f9000-ec21-11e9-86e3-1f67c7825e32.png)

**Comment by ch-nry** [comment]
The message is a bit alarming : both module works with all SR, but the algorithm/sound was optimized for a specific SR.  (The code was design for a specific hardware, and is only "port" to VCV.)  

My aim porting this module to VCV is to have the exact sound of the hardware. It will not be the same if I resample the in/out to work with other SR.

On the original hardware, you can only have 1 module on the same time anyway...

So, this is a limitation, but not a bug.

**Comment by vcvrackideas** [comment]
Yes, of course, I understand the thing about a limitation. But I really don't get a thing that design of your panels should suffers from that. Maybe those warnings may be just a pop-ups for 2 seconds?

**Comment by ch-nry** [comment]
that's a good idea. 
will do when I have time...

**Comment by ch-nry** [comment]
update with commit 88483049ea016d2b1dc38a88f160d98373d38ff4
