### ISSUE TITLE
Tips for using V/O on SIN AM and SIN FM

### ISSUE THREAD

**Issue by mattcollier** [ch-nry/VCV_nozori#8]
Hello, I'm having difficulty getting useful sounds out of these modules when using the V/O input.  I'm finding that V/O values above 0 almost always produce results above 20kHz and many of the negative V/O produce results in that range as well.  Am I doing something wrong or is it just that these modules are not meant to be "played" with note CV?

**Comment by ch-nry** [comment]
This look like a bug. Thanks for the report.
I'll investigate and propose a fix soon.

**Comment by ch-nry** [comment]
should be fixed with commit : 87a28a17c3a0f2289b365214290be60ea3fc9052
