### ISSUE TITLE
SIN FM V/O tracking in v1.1.4

### ISSUE THREAD

**Issue by mattcollier** [ch-nry/VCV_nozori#9]
Hello, I received the 1.1.4 update today.

It appears that now the effective range is between -6V and -2V with a frequency range of 1.2kHz and 21kHz with all the FQ knobs at minimum.  Is this the proper behavior?

I've attached a patch.
[sin_fm_demo.vcv.zip](https://github.com/ch-nry/VCV_nozori/files/4372688/sin_fm_demo.vcv.zip)

**Comment by ch-nry** [comment]
Hello Matt,
No, this is not the range I get with your patch:
- without any CV input, the FQ1 knobs range the frequency from very low (<20Hz) to 12KHz.
- without any CV input, FQ1 in the middle result in a 300Hz frequency
- with a 0V CV input, the frequency is not altered
- with FQ1 in the middle position, the CV input range from -6 to 6V. The frequency goes from 6 Oct bellow 300Hz (i.e : 4Hz) to 6 Oct above 300Hz (i.e about 20KHz)

This is the proper behaviour when using a sampling rate of 96KHz. 

![Capture du 2020-03-24 08-56-47](https://user-images.githubusercontent.com/1230363/77401592-7c46b580-6dad-11ea-878a-4e9b6dcd8917.png)

what platform are you using?

**Comment by mattcollier** [comment]
Hello, confirmed working properly as you described this morning. I retraced my steps to see if there were issues related to changing the sample rate etc.  Not sure what happened yesterday. I'm on Ubuntu Studio 18.04.  Thank you!
